version: "2"
services:
  wc:
    restart: unless-stopped
    image: "ghcr.io/weeb-network/wc:main"
    ports:
    #IMPORTANT: DO NOT CHANGE THE 8080 PART ONLY CHANGE THE <your port here> PART
      - <your port here>:8080
